### ISSUE TITLE
Проблема 

### ISSUE THREAD

**Issue by ddos-pro** [Bainky/Telegram-RAT#18]
C:\Users\User\Desktop\Telegram-RAT-master>python RAT.py
[+] > Подключено
2020-05-20 16:42:10,631 (util.py:66 PollingThread) ERROR - TeleBot: "ConnectTime
out occurred, args=(MaxRetryError("SOCKSHTTPSConnectionPool(host='api.telegram.o
rg', port=443): Max retries exceeded with url: /bot645317982:AAEwjt8sSb3IlOGhOdu
mcPoK7mjkhdgGnBE/getUpdates?offset=1&timeout=20 (Caused by ConnectTimeoutError(<
urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0628CE30>, 'Connection to
 api.telegram.org timed out. (connect timeout=3.5)'))",),)
Traceback (most recent call last):
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 809, in c
onnect
    negotiate(self, dest_addr, dest_port)
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 444, in _
negotiate_SOCKS5
    self, CONNECT, dest_addr)
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 524, in _
SOCKS5_request
    resp = self._readall(reader, 3)
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 276, in _
readall
    d = file.read(count - len(data))
  File "C:\Program Files\Python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\contrib\socks.py"
, line 99, in _new_conn
    **extra_kw
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 209, in c
reate_connection
    raise err
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 199, in c
reate_connection
    sock.connect((remote_host, remote_port))
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 47, in wr
apper
    return function(*args, **kwargs)
  File "C:\Program Files\Python36-32\lib\site-packages\socks.py", line 814, in c
onnect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\connectionpool.py
", line 677, in urlopen
    chunked=chunked,
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\connectionpool.py
", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\connectionpool.py
", line 976, in _validate_conn
    conn.connect()
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\connection.py", l
ine 308, in connect
    conn = self._new_conn()
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\contrib\socks.py"
, line 118, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.contrib.socks.SOCKSHTTPSConnec
tion object at 0x0628CE30>, 'Connection to api.telegram.org timed out. (connect
timeout=3.5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36-32\lib\site-packages\requests\adapters.py", li
ne 449, in send
    timeout=timeout
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\connectionpool.py
", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files\Python36-32\lib\site-packages\urllib3\util\retry.py", l
ine 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.telegram.or
g', port=443): Max retries exceeded with url: /bot645317982:AAEwjt8sSb3IlOGhOdum
cPoK7mjkhdgGnBE/getUpdates?offset=1&timeout=20 (Caused by ConnectTimeoutError(<u
rllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0628CE30>, 'Connection to
api.telegram.org timed out. (connect timeout=3.5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36-32\lib\site-packages\telebot\util.py", line 60
, in run
    task(*args, **kwargs)
  File "C:\Program Files\Python36-32\lib\site-packages\telebot\__init__.py", lin
e 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout
)
  File "C:\Program Files\Python36-32\lib\site-packages\telebot\__init__.py", lin
e 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, all
owed_updates)
  File "C:\Program Files\Python36-32\lib\site-packages\telebot\apihelper.py", li
ne 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Program Files\Python36-32\lib\site-packages\telebot\apihelper.py", li
ne 58, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Program Files\Python36-32\lib\site-packages\requests\sessions.py", li
ne 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python36-32\lib\site-packages\requests\sessions.py", li
ne 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36-32\lib\site-packages\requests\adapters.py", li
ne 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: SOCKSHTTPSConnectionPool(host='api.telegram.
org', port=443): Max retries exceeded with url: /bot645317982:AAEwjt8sSb3IlOGhOd
umcPoK7mjkhdgGnBE/getUpdates?offset=1&timeout=20 (Caused by ConnectTimeoutError(
<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0628CE30>, 'Connection t
o api.telegram.org timed out. (connect timeout=3.5)'))
"

**Comment by ddos-pro** [comment]
и краш

**Comment by MekoNix** [comment]
У вас не могут подключиться прокси socks. Попробуйте установить обычный VPN клиент и запустить предварительно убрав из файла программы адрес прокси.

**Comment by MekoNix** [comment]
Также проверьте  правильность api бота или просто создайте новый.

**Comment by ddos-pro** [comment]
да спасибо, уже решил проблему, поменял api ссылки в telebot на аналогичный русский
