### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by azatka** [Bainky/Telegram-RAT#4]
Привет, в чем может быть проблема?
`C:\Users\admin\Downloads>pyinstaller RAT.py
268 INFO: PyInstaller: 3.6
269 INFO: Python: 3.8.2
276 INFO: Platform: Windows-10-10.0.14393-SP0
278 INFO: wrote C:\Users\admin\Downloads\RAT.spec
284 INFO: UPX is not available.
289 INFO: Extending PYTHONPATH with paths
['C:\\Users\\admin\\Downloads', 'C:\\Users\\admin\\Downloads']
290 INFO: checking Analysis
291 INFO: Building Analysis because Analysis-00.toc is non existent
298 INFO: Initializing module dependency graph...
314 INFO: Caching module graph hooks...
355 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\pkgutil.py", line 130, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\pkgutil.py", line 149, in _iter_file_finder_modules
    import inspect
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\inspect.py", line 40, in <module>
    import linecache
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\tokenize.py", line 32, in <module>
    import re
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\pkgutil.py", line 130, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\pkgutil.py", line 149, in _iter_file_finder_modules
    import inspect
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\inspect.py", line 40, in <module>
    import linecache
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\tokenize.py", line 32, in <module>
    import re
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
10894 INFO: Processing pre-find module path hook   distutils
10897 INFO: distutils: retargeting to non-venv dir 'c:\\users\\admin\\appdata\\local\\programs\\python\\python38-32\\lib'
23028 INFO: Caching module dependency graph...
23834 INFO: running Analysis Analysis-00.toc
23896 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\admin\appdata\local\programs\python\python38-32\python.exe
25093 INFO: Analyzing C:\Users\admin\Downloads\RAT.py
27293 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\urllib3-1.25.8-py3.8.egg\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\urllib3-1.25.8-py3.8.egg\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "c:\users\admin\appdata\local\programs\python\python38-32\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
pre-safe-import-module hook failed, needs fixing.`

**Comment by AndrijCat** [comment]
`pip uninstall -y enum34`


[источник](https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag)
